### ISSUE TITLE
Segfault in CCharacter::TakeDamage

### ISSUE THREAD

**Issue by def-** [ddnet/zcatch#3]
```
Core was generated by `./zCatch-Server_sql -f servers/8400.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055be3a788364 in CCharacter::TakeDamage (this=0x55be3a870150 <ms_PoolDataCCharacter+1808>, Force=..., Force@entry=..., Dmg=6, From=From@entry=1, Weapon=Weapon@entry=3)
    at src/game/server/entities/character.cpp:888
888		if(g_Config.m_SvRespawnProtection && From >= 0 && (m_pPlayer->m_RespawnProtection > Server()->Tick() || GameServer()->m_apPlayers[From]->m_RespawnProtection > Server()->Tick()))
[Current thread is 1 (LWP 18014)]
(gdb) bt
#0  0x000055be3a788364 in CCharacter::TakeDamage (this=0x55be3a870150 <ms_PoolDataCCharacter+1808>, Force=..., Force@entry=..., Dmg=6, From=From@entry=1, Weapon=Weapon@entry=3)
    at src/game/server/entities/character.cpp:888
#1  0x000055be3a77bad6 in CGameContext::CreateExplosion (this=0x55be3af180a0, Pos=..., Owner=1, Weapon=3, NoDamage=NoDamage@entry=false, limitVictims=true, victims=victims@entry=0x55be3afaab99)
    at src/game/server/gamecontext.cpp:155
#2  0x000055be3a786311 in CProjectile::Tick (this=0x55be3afaab60) at src/game/server/entities/projectile.cpp:76
#3  0x000055be3a78a445 in CGameWorld::Tick (this=this@entry=0x55be3af1ae40) at src/game/server/gameworld.cpp:164
#4  0x000055be3a77fff7 in CGameContext::OnTick (this=0x55be3af180a0) at src/game/server/gamecontext.cpp:434
#5  0x000055be3a76f873 in CServer::Run (this=this@entry=0x7f575fb10010) at src/engine/server/server.h:92
#6  0x000055be3a74e9d0 in main (argc=3, argv=0x7ffe7b31cf18) at src/engine/server/server.cpp:2362
```

**Comment by def-** [comment]
I think I see the issue, will provide a fix.
